apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-custom-hpa
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: test_fastapi_request_response_metrics_per_2m
      target:
        type: AverageValue
        averageValue: 300m
  behavior:
    scaleDown:
      selectPolicy: Disabled