apiVersion: v1
kind: Service
metadata:
    name: duncan-fastapi
    namespace: monitoring
    labels:
        k8s-app: duncan-fastapi
        release: prometheus
spec:
    type: ClusterIP
    ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080